replaced all miso with pe_miso, replaced all MISO with PE_MISO

diff --git a/initcpio/hooks/miso_pxe_nfs b/initcpio/hooks/miso_pxe_nfs
--- a/initcpio/hooks/miso_pxe_nfs
+++ b/initcpio/hooks/miso_pxe_nfs
@@ -1,22 +1,22 @@
 # vim: set ft=sh:
 
 run_hook() {
-    if [[ -n "${ip}" && -n "${miso_nfs_srv}" ]]; then
+    if [[ -n "${ip}" && -n "${pe_miso_nfs_srv}" ]]; then
 
-        miso_nfs_srv=$(eval echo ${miso_nfs_srv})
-        [[ -n "${miso_nfs_opt}" ]] && miso_nfs_opt="-o ${miso_nfs_opt}"
+        pe_miso_nfs_srv=$(eval echo ${pe_miso_nfs_srv})
+        [[ -n "${pe_miso_nfs_opt}" ]] && pe_miso_nfs_opt="-o ${pe_miso_nfs_opt}"
 
-        mount_handler="miso_nfs_mount_handler"
+        mount_handler="pe_miso_nfs_mount_handler"
     fi
 }
 
-miso_nfs_mount_handler() {
+pe_miso_nfs_mount_handler() {
     newroot="${1}"
-    mkdir -p "/run/miso/bootmnt"
-    msg ":: Mounting '${miso_nfs_srv}'"
-    # Do not put "${miso_nfs_opt}" nfsmount fails!
-    if ! nfsmount ${miso_nfs_opt} "${miso_nfs_srv}" "/run/miso/bootmnt"; then
-        echo "ERROR: Mounting '${miso_nfs_srv}'"
+    mkdir -p "/run/pe_miso/bootmnt"
+    msg ":: Mounting '${pe_miso_nfs_srv}'"
+    # Do not put "${pe_miso_nfs_opt}" nfsmount fails!
+    if ! nfsmount ${pe_miso_nfs_opt} "${pe_miso_nfs_srv}" "/run/pe_miso/bootmnt"; then
+        echo "ERROR: Mounting '${pe_miso_nfs_srv}'"
         echo "   Falling back to interactive prompt"
         echo "   You can try to fix the problem manually, log out when you are finished"
         launch_interactive_shell
@@ -26,5 +26,5 @@ miso_nfs_mount_handler() {
         copytoram="y"
     fi
 
-    miso_mount_handler ${newroot}
+    pe_miso_mount_handler ${newroot}
 }
